config/routes.rb
Rails.application.routes.draw do
  #devise_for :users
	#devise_for :user_ayv, :controllers => {:confirmations => "entre_azul_y_verde/devise/confirmations", :passwords => "entre_azul_y_verde/devise/passwords", :registrations => "entre_azul_y_verde/devise/registrations", :unlocks => "entre_azul_y_verde/devise/unlocks", :sessions => "entre_azul_y_verde/devise/sessions"}
  #devise_for :user_mn, :controllers => {:confirmations => "mosaico_natura/devise/confirmations", :passwords => "mosaico_natura/devise/passwords", :registrations => "mosaico_natura/devise/registrations", :unlocks => "mosaico_natura/devise/unlocks", :sessions => "mosaico_natura/devise/sessions"}
	
	resources :cat_concursos
	resources :media_metadatos
	resources :usuario_metadatos
	resources :cat_metadatos
	resources :direcciones
	resources :categorias
	resources :usuarios
	resources :medias
	resources :calificaciones
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	
	
	if Rails.env.development?
		namespace 'entre_azul_y_verde' do
			root 'inicio#index'
			get 'quees' => 'inicio#index'
			get 'categorias' => 'inicio#index'
			get 'medios' => 'inicio#index'
			
			get 'bases' => 'inicio#bases'
			get '/galerias/index'
			get '/galerias/' => 'galerias#index'
			
      resources :panel do
				collection do
					get :precalificacion
					get :calificacion
          get :desempate
        end
      end
    end
		
		namespace 'mosaico_natura' do
			root 'inicio#index'
			get 'quees' => 'inicio#index'
			get 'categorias' => 'inicio#index'
			get 'medios' => 'inicio#index'
			get 'bases' => 'inicio#bases'
			get 'terminos_condiciones' => 'inicio#terminos_condiciones'
			get '/galerias/index'
			get '/galerias/' => 'galerias#index'
			resources :panel do
				collection do
					get :calificacion
					get :desempate
					get :ganadores
					get :todos
				end
			end
    end

	else
		constraints(lambda { |request| ['entreazulyverde.mx','www.entreazulyverde.mx'].include?(request.host) }) do
			root 'entre_azul_y_verde/inicio#index'
			namespace 'entre_azul_y_verde' do
				root 'inicio#index'
				get 'quees' => 'inicio#index'
				get 'categorias' => 'inicio#index'
				get 'medios' => 'inicio#index'
				
				get 'bases' => 'inicio#bases'
				get '/galerias/index'
				get '/galerias/' => 'galerias#index'
				resources :panel do
					collection do
						get :precalificacion
						get :calificacion
						get :desempate
					end
				end
			end
		end
		
		constraints(lambda { |request| ['mosaiconatura.net','www.mosaiconatura.net'].include?(request.host) }) do
			root 'mosaico_natura/inicio#index'
			namespace 'mosaico_natura' do
				root 'inicio#index'
				get 'quees' => 'inicio#index'
				get 'categorias' => 'inicio#index'
				get 'medios' => 'inicio#index'
				get 'bases' => 'inicio#bases'
				get 'terminos_condiciones' => 'inicio#terminos_condiciones'
				get '/galerias/index'
				get '/galerias/' => 'galerias#index'
				resources :galerias
				resources :panel do
					collection do
						get :calificacion
						get :desempate
						get :ganadores
						get :todos
					end
				end
			end
		end
	end



end

app/models/cat_concurso.rb
class CatConcurso < ApplicationRecord
end

app/controllers/cat_concursos_controller.rb
class CatConcursosController < ApplicationController
  before_action :set_cat_concurso, only: %i[ show edit update destroy ]

  # GET /cat_concursos or /cat_concursos.json
  def index
    @cat_concursos = CatConcurso.all
  end

  # GET /cat_concursos/1 or /cat_concursos/1.json
  def show
  end

  # GET /cat_concursos/new
  def new
    @cat_concurso = CatConcurso.new
  end

  # GET /cat_concursos/1/edit
  def edit
  end

  # POST /cat_concursos or /cat_concursos.json
  def create
    @cat_concurso = CatConcurso.new(cat_concurso_params)

    respond_to do |format|
      if @cat_concurso.save
        format.html { redirect_to @cat_concurso, notice: "Cat concurso was successfully created." }
        format.json { render :show, status: :created, location: @cat_concurso }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cat_concurso.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cat_concursos/1 or /cat_concursos/1.json
  def update
    respond_to do |format|
      if @cat_concurso.update(cat_concurso_params)
        format.html { redirect_to @cat_concurso, notice: "Cat concurso was successfully updated." }
        format.json { render :show, status: :ok, location: @cat_concurso }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cat_concurso.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cat_concursos/1 or /cat_concursos/1.json
  def destroy
    @cat_concurso.destroy
    respond_to do |format|
      format.html { redirect_to cat_concursos_url, notice: "Cat concurso was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cat_concurso
      @cat_concurso = CatConcurso.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cat_concurso_params
      params.require(:cat_concurso).permit(:nombre_concurso, :descripcion_concurso)
    end
end

app/helpers/cat_concursos_helper.rb
module CatConcursosHelper
end

app/views/cat_concursos/_form.html.erb
<%= form_with(model: cat_concurso, local: true) do |form| %>
  <% if cat_concurso.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cat_concurso.errors.count, "error") %> prohibited this cat_concurso from being saved:</h2>

      <ul>
      <% cat_concurso.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre_concurso %>
    <%= form.text_field :nombre_concurso, id: :cat_concurso_nombre_concurso %>
  </div>

  <div class="field">
    <%= form.label :descripcion_concurso %>
    <%= form.text_area :descripcion_concurso, id: :cat_concurso_descripcion_concurso %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cat_concursos/edit.html.erb
<h1>Editing Cat Concurso</h1>

<%= render 'form', cat_concurso: @cat_concurso %>

<%= link_to 'Show', @cat_concurso %> |
<%= link_to 'Back', cat_concursos_path %>

app/views/cat_concursos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cat Concursos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre concurso</th>
      <th>Descripcion concurso</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cat_concursos.each do |cat_concurso| %>
      <tr>
        <td><%= cat_concurso.nombre_concurso %></td>
        <td><%= cat_concurso.descripcion_concurso %></td>
        <td><%= link_to 'Show', cat_concurso %></td>
        <td><%= link_to 'Edit', edit_cat_concurso_path(cat_concurso) %></td>
        <td><%= link_to 'Destroy', cat_concurso, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cat Concurso', new_cat_concurso_path %>

app/views/cat_concursos/new.html.erb
<h1>New Cat Concurso</h1>

<%= render 'form', cat_concurso: @cat_concurso %>

<%= link_to 'Back', cat_concursos_path %>

app/views/cat_concursos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre concurso:</strong>
  <%= @cat_concurso.nombre_concurso %>
</p>

<p>
  <strong>Descripcion concurso:</strong>
  <%= @cat_concurso.descripcion_concurso %>
</p>

<%= link_to 'Edit', edit_cat_concurso_path(@cat_concurso) %> |
<%= link_to 'Back', cat_concursos_path %>