config/routes.rb
Rails.application.routes.draw do
  #devise_for :users
	#devise_for :user_ayv, :controllers => {:confirmations => "entre_azul_y_verde/devise/confirmations", :passwords => "entre_azul_y_verde/devise/passwords", :registrations => "entre_azul_y_verde/devise/registrations", :unlocks => "entre_azul_y_verde/devise/unlocks", :sessions => "entre_azul_y_verde/devise/sessions"}
  #devise_for :user_mn, :controllers => {:confirmations => "mosaico_natura/devise/confirmations", :passwords => "mosaico_natura/devise/passwords", :registrations => "mosaico_natura/devise/registrations", :unlocks => "mosaico_natura/devise/unlocks", :sessions => "mosaico_natura/devise/sessions"}
	
	resources :cat_concursos
	resources :media_metadatos
	resources :usuario_metadatos
	resources :cat_metadatos
	resources :direcciones
	resources :categorias
	resources :usuarios
	resources :medias
	resources :calificaciones
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	
	
	if Rails.env.development?
		namespace 'entre_azul_y_verde' do
			root 'inicio#index'
			get 'quees' => 'inicio#index'
			get 'categorias' => 'inicio#index'
			get 'medios' => 'inicio#index'
			
			get 'bases' => 'inicio#bases'
			get '/galerias/index'
			get '/galerias/' => 'galerias#index'
			
      resources :panel do
				collection do
					get :precalificacion
					get :calificacion
          get :desempate
        end
      end
    end
		
		namespace 'mosaico_natura' do
			root 'inicio#index'
			get 'quees' => 'inicio#index'
			get 'categorias' => 'inicio#index'
			get 'medios' => 'inicio#index'
			get 'bases' => 'inicio#bases'
			get 'terminos_condiciones' => 'inicio#terminos_condiciones'
			get '/galerias/index'
			get '/galerias/' => 'galerias#index'
			resources :panel do
				collection do
					get :calificacion
					get :desempate
					get :ganadores
					get :todos
				end
			end
    end

	else
		constraints(lambda { |request| ['entreazulyverde.mx','www.entreazulyverde.mx'].include?(request.host) }) do
			root 'entre_azul_y_verde/inicio#index'
			namespace 'entre_azul_y_verde' do
				root 'inicio#index'
				get 'quees' => 'inicio#index'
				get 'categorias' => 'inicio#index'
				get 'medios' => 'inicio#index'
				
				get 'bases' => 'inicio#bases'
				get '/galerias/index'
				get '/galerias/' => 'galerias#index'
				resources :panel do
					collection do
						get :precalificacion
						get :calificacion
						get :desempate
					end
				end
			end
		end
		
		constraints(lambda { |request| ['mosaiconatura.net','www.mosaiconatura.net'].include?(request.host) }) do
			root 'mosaico_natura/inicio#index'
			namespace 'mosaico_natura' do
				root 'inicio#index'
				get 'quees' => 'inicio#index'
				get 'categorias' => 'inicio#index'
				get 'medios' => 'inicio#index'
				get 'bases' => 'inicio#bases'
				get 'terminos_condiciones' => 'inicio#terminos_condiciones'
				get '/galerias/index'
				get '/galerias/' => 'galerias#index'
				resources :galerias
				resources :panel do
					collection do
						get :calificacion
						get :desempate
						get :ganadores
						get :todos
					end
				end
			end
		end
	end



end

app/controllers/direcciones_controller.rb
class DireccionesController < ApplicationController
  before_action :set_direccion, only: %i[ show edit update destroy ]

  # GET /direcciones or /direcciones.json
  def index
    @direcciones = Direccion.all
  end

  # GET /direcciones/1 or /direcciones/1.json
  def show
  end

  # GET /direcciones/new
  def new
    @direccion = Direccion.new
  end

  # GET /direcciones/1/edit
  def edit
  end

  # POST /direcciones or /direcciones.json
  def create
    @direccion = Direccion.new(direccion_params)

    respond_to do |format|
      if @direccion.save
        format.html { redirect_to @direccion, notice: "Direccion was successfully created." }
        format.json { render :show, status: :created, location: @direccion }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @direccion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /direcciones/1 or /direcciones/1.json
  def update
    respond_to do |format|
      if @direccion.update(direccion_params)
        format.html { redirect_to @direccion, notice: "Direccion was successfully updated." }
        format.json { render :show, status: :ok, location: @direccion }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @direccion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /direcciones/1 or /direcciones/1.json
  def destroy
    @direccion.destroy
    respond_to do |format|
      format.html { redirect_to direcciones_url, notice: "Direccion was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_direccion
      @direccion = Direccion.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def direccion_params
      params.require(:direccion).permit(:calle, :numero, :interior, :colonia, :municipio, :cp, :estado, :id_usuario)
    end
end

app/helpers/direcciones_helper.rb
module DireccionesHelper
end

app/views/direcciones/_form.html.erb
<%= form_with(model: direccion, local: true) do |form| %>
  <% if direccion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(direccion.errors.count, "error") %> prohibited this direccion from being saved:</h2>

      <ul>
      <% direccion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :calle %>
    <%= form.text_field :calle, id: :direccion_calle %>
  </div>

  <div class="field">
    <%= form.label :numero %>
    <%= form.number_field :numero, id: :direccion_numero %>
  </div>

  <div class="field">
    <%= form.label :interior %>
    <%= form.text_field :interior, id: :direccion_interior %>
  </div>

  <div class="field">
    <%= form.label :colonia %>
    <%= form.text_field :colonia, id: :direccion_colonia %>
  </div>

  <div class="field">
    <%= form.label :municipio %>
    <%= form.text_field :municipio, id: :direccion_municipio %>
  </div>

  <div class="field">
    <%= form.label :cp %>
    <%= form.text_field :cp, id: :direccion_cp %>
  </div>

  <div class="field">
    <%= form.label :estado %>
    <%= form.text_field :estado, id: :direccion_estado %>
  </div>

  <div class="field">
    <%= form.label :id_usuario %>
    <%= form.number_field :id_usuario, id: :direccion_id_usuario %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/direcciones/_form_direccion.html.erb
<div class='nested-fields'>
	<%= f.input_field :calle, class: 'form-control my-2', placeholder: 'Calle' %>
	<%= f.input_field :numero, class: 'form-control my-2', placeholder: 'Número' %>
	<%= f.input_field :interior, class: 'form-control my-2', placeholder: 'Interior' %>
	<%= f.input_field :colonia, class: 'form-control my-2', placeholder: 'Colonia' %>
	<%= f.input_field :municipio, class: 'form-control my-2', placeholder: 'Municipio/Alcaldía' %>
	<%= f.input_field :cp, class: 'form-control my-2', placeholder: 'Código postal' %>
	<%= f.input_field :estado, class: 'form-control my-2', placeholder: 'Estado' %>
	<%#= link_to_remove_association "Quita dirección", f, class: 'btn btn-danger btn-sm' %>
</div>

app/views/direcciones/edit.html.erb
<h1>Editing Direccion</h1>

<%= render 'form', direccion: @direccion %>

<%= link_to 'Show', @direccion %> |
<%= link_to 'Back', direcciones_path %>

app/views/direcciones/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Direcciones</h1>

<table>
  <thead>
    <tr>
      <th>Calle</th>
      <th>Numero</th>
      <th>Interior</th>
      <th>Colonia</th>
      <th>Municipio</th>
      <th>Cp</th>
      <th>Estado</th>
      <th>Id usuario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @direcciones.each do |direccion| %>
      <tr>
        <td><%= direccion.calle %></td>
        <td><%= direccion.numero %></td>
        <td><%= direccion.interior %></td>
        <td><%= direccion.colonia %></td>
        <td><%= direccion.municipio %></td>
        <td><%= direccion.cp %></td>
        <td><%= direccion.estado %></td>
        <td><%= direccion.id_usuario %></td>
        <td><%= link_to 'Show', direccion %></td>
        <td><%= link_to 'Edit', edit_direccion_path(direccion) %></td>
        <td><%= link_to 'Destroy', direccion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Direccion', new_direccion_path %>

app/views/direcciones/new.html.erb
<h1>New Direccion</h1>

<%= render 'form', direccion: @direccion %>

<%= link_to 'Back', direcciones_path %>

app/views/direcciones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Calle:</strong>
  <%= @direccion.calle %>
</p>

<p>
  <strong>Numero:</strong>
  <%= @direccion.numero %>
</p>

<p>
  <strong>Interior:</strong>
  <%= @direccion.interior %>
</p>

<p>
  <strong>Colonia:</strong>
  <%= @direccion.colonia %>
</p>

<p>
  <strong>Municipio:</strong>
  <%= @direccion.municipio %>
</p>

<p>
  <strong>Cp:</strong>
  <%= @direccion.cp %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @direccion.estado %>
</p>

<p>
  <strong>Id usuario:</strong>
  <%= @direccion.id_usuario %>
</p>

<%= link_to 'Edit', edit_direccion_path(@direccion) %> |
<%= link_to 'Back', direcciones_path %>