config/routes.rb
Rails.application.routes.draw do
  #devise_for :users
	#devise_for :user_ayv, :controllers => {:confirmations => "entre_azul_y_verde/devise/confirmations", :passwords => "entre_azul_y_verde/devise/passwords", :registrations => "entre_azul_y_verde/devise/registrations", :unlocks => "entre_azul_y_verde/devise/unlocks", :sessions => "entre_azul_y_verde/devise/sessions"}
  #devise_for :user_mn, :controllers => {:confirmations => "mosaico_natura/devise/confirmations", :passwords => "mosaico_natura/devise/passwords", :registrations => "mosaico_natura/devise/registrations", :unlocks => "mosaico_natura/devise/unlocks", :sessions => "mosaico_natura/devise/sessions"}
	
	resources :cat_concursos
	resources :media_metadatos
	resources :usuario_metadatos
	resources :cat_metadatos
	resources :direcciones
	resources :categorias
	resources :usuarios
	resources :medias
	resources :calificaciones
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	
	
	if Rails.env.development?
		namespace 'entre_azul_y_verde' do
			root 'inicio#index'
			get 'quees' => 'inicio#index'
			get 'categorias' => 'inicio#index'
			get 'medios' => 'inicio#index'
			
			get 'bases' => 'inicio#bases'
			get '/galerias/index'
			get '/galerias/' => 'galerias#index'
			
      resources :panel do
				collection do
					get :precalificacion
					get :calificacion
          get :desempate
        end
      end
    end
		
		namespace 'mosaico_natura' do
			root 'inicio#index'
			get 'quees' => 'inicio#index'
			get 'categorias' => 'inicio#index'
			get 'medios' => 'inicio#index'
			get 'bases' => 'inicio#bases'
			get 'terminos_condiciones' => 'inicio#terminos_condiciones'
			get '/galerias/index'
			get '/galerias/' => 'galerias#index'
			resources :panel do
				collection do
					get :calificacion
					get :desempate
					get :ganadores
					get :todos
				end
			end
    end

	else
		constraints(lambda { |request| ['entreazulyverde.mx','www.entreazulyverde.mx'].include?(request.host) }) do
			root 'entre_azul_y_verde/inicio#index'
			namespace 'entre_azul_y_verde' do
				root 'inicio#index'
				get 'quees' => 'inicio#index'
				get 'categorias' => 'inicio#index'
				get 'medios' => 'inicio#index'
				
				get 'bases' => 'inicio#bases'
				get '/galerias/index'
				get '/galerias/' => 'galerias#index'
				resources :panel do
					collection do
						get :precalificacion
						get :calificacion
						get :desempate
					end
				end
			end
		end
		
		constraints(lambda { |request| ['mosaiconatura.net','www.mosaiconatura.net'].include?(request.host) }) do
			root 'mosaico_natura/inicio#index'
			namespace 'mosaico_natura' do
				root 'inicio#index'
				get 'quees' => 'inicio#index'
				get 'categorias' => 'inicio#index'
				get 'medios' => 'inicio#index'
				get 'bases' => 'inicio#bases'
				get 'terminos_condiciones' => 'inicio#terminos_condiciones'
				get '/galerias/index'
				get '/galerias/' => 'galerias#index'
				resources :galerias
				resources :panel do
					collection do
						get :calificacion
						get :desempate
						get :ganadores
						get :todos
					end
				end
			end
		end
	end



end

app/models/cat_metadato.rb
class CatMetadato < ApplicationRecord
	
	has_many :media_metadatos, foreign_key: :metadato_id
	has_many :usuario_metadatos, foreign_key: :metadato_id
	
end

app/controllers/cat_metadatos_controller.rb
class CatMetadatosController < ApplicationController
  before_action :set_cat_metadato, only: %i[ show edit update destroy ]

  # GET /cat_metadatos or /cat_metadatos.json
  def index
    @cat_metadatos = CatMetadato.all
  end

  # GET /cat_metadatos/1 or /cat_metadatos/1.json
  def show
  end

  # GET /cat_metadatos/new
  def new
    @cat_metadato = CatMetadato.new
  end

  # GET /cat_metadatos/1/edit
  def edit
  end

  # POST /cat_metadatos or /cat_metadatos.json
  def create
    @cat_metadato = CatMetadato.new(cat_metadato_params)

    respond_to do |format|
      if @cat_metadato.save
        format.html { redirect_to @cat_metadato, notice: "Cat metadato was successfully created." }
        format.json { render :show, status: :created, location: @cat_metadato }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cat_metadato.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cat_metadatos/1 or /cat_metadatos/1.json
  def update
    respond_to do |format|
      if @cat_metadato.update(cat_metadato_params)
        format.html { redirect_to @cat_metadato, notice: "Cat metadato was successfully updated." }
        format.json { render :show, status: :ok, location: @cat_metadato }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cat_metadato.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cat_metadatos/1 or /cat_metadatos/1.json
  def destroy
    @cat_metadato.destroy
    respond_to do |format|
      format.html { redirect_to cat_metadatos_url, notice: "Cat metadato was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cat_metadato
      @cat_metadato = CatMetadato.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cat_metadato_params
      params.require(:cat_metadato).permit(:nombre_metadato, :descripcion, :ancestry)
    end
end

app/helpers/cat_metadatos_helper.rb
module CatMetadatosHelper
end

app/views/cat_metadatos/_form.html.erb
<%= form_with(model: cat_metadato, local: true) do |form| %>
  <% if cat_metadato.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cat_metadato.errors.count, "error") %> prohibited this cat_metadato from being saved:</h2>

      <ul>
      <% cat_metadato.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre_metadato %>
    <%= form.text_field :nombre_metadato, id: :cat_metadato_nombre_metadato %>
  </div>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_field :descripcion, id: :cat_metadato_descripcion %>
  </div>

  <div class="field">
    <%= form.label :ancestry %>
    <%= form.text_field :ancestry, id: :cat_metadato_ancestry %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cat_metadatos/edit.html.erb
<h1>Editing Cat Metadato</h1>

<%= render 'form', cat_metadato: @cat_metadato %>

<%= link_to 'Show', @cat_metadato %> |
<%= link_to 'Back', cat_metadatos_path %>

app/views/cat_metadatos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cat Metadatos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre metadato</th>
      <th>Descripcion</th>
      <th>Ancestry</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cat_metadatos.each do |cat_metadato| %>
      <tr>
        <td><%= cat_metadato.nombre_metadato %></td>
        <td><%= cat_metadato.descripcion %></td>
        <td><%= cat_metadato.ancestry %></td>
        <td><%= link_to 'Show', cat_metadato %></td>
        <td><%= link_to 'Edit', edit_cat_metadato_path(cat_metadato) %></td>
        <td><%= link_to 'Destroy', cat_metadato, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cat Metadato', new_cat_metadato_path %>

app/views/cat_metadatos/new.html.erb
<h1>New Cat Metadato</h1>

<%= render 'form', cat_metadato: @cat_metadato %>

<%= link_to 'Back', cat_metadatos_path %>

app/views/cat_metadatos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre metadato:</strong>
  <%= @cat_metadato.nombre_metadato %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @cat_metadato.descripcion %>
</p>

<p>
  <strong>Ancestry:</strong>
  <%= @cat_metadato.ancestry %>
</p>

<%= link_to 'Edit', edit_cat_metadato_path(@cat_metadato) %> |
<%= link_to 'Back', cat_metadatos_path %>